spool michael_chen.log

PROMPT PRACTICA - MICHAEL CHEN WANG

HOST CLS
CONNECT system/root

PROMPT PARTE 1
PROMPT CREANDO PERMISOS MINIMOS
DROP USER RAMIRO CASCADE;
DROP USER MARIA  CASCADE;
DROP USER BOBY	 CASCADE;
DROP USER TOMMY  CASCADE;


PROMPT DROPPING ROLES
DROP ROLE VET_CONSULTA;
DROP ROLE VET_PROCESO;
DROP ROLE VET_GERENTE;
DROP ROLE EMP_SEL;
DROP ROLE EMP_JEFE;
DROP ROLE EMP_PROCESO;


PROMPT DROPPING SYNONYMS
DROP PUBLIC SYNONYM TAB_MASCOTAS;
DROP PUBLIC SYNONYM INS_MASCOTAS;
DROP PUBLIC SYNONYM EMPLEADOS3;
DROP PUBLIC SYNONYM PRC_INS_EMPLEADOS3;


CREATE USER RAMIRO IDENTIFIED BY RAMIRO123;
CREATE USER MARIA  IDENTIFIED BY MARIA123;
CREATE USER BOBY   IDENTIFIED BY BOBY123;
CREATE USER TOMMY  IDENTIFIED BY TOMMY123;


GRANT CREATE SESSION        TO RAMIRO;
GRANT CREATE TABLE          TO RAMIRO;
GRANT CREATE ROLES          TO RAMIRO;
GRANT CREATE PROCEDURE      TO RAMIRO;
GRANT CREATE PUBLIC SYNONYM TO RAMIRO;

GRANT CREATE SESSION        TO MARIA;
GRANT CREATE TABLE          TO MARIA;
GRANT CREATE ROLES          TO MARIA;
GRANT CREATE PROCEDURE      TO MARIA;
GRANT CREATE PUBLIC SYNONYM TO MARIA;

GRANT CREATE SESSION TO BOBY; 
GRANT CREATE SESSION TO TOMMY;

ALTER USER RAMIRO QUOTA UNLIMITED ON SYSTEM;
ALTER USER MARIA  QUOTA UNLIMITED ON SYSTEM;


PROMPT CONNECTANDOSE COMO RAMIRO
CONNECT RAMIRO/RAMIRO123;


CREATE TABLE MASCOTAS ( ID            NUMBER(2), 
                      APODO_MASCOTA VARCHAR2(10), 
                      ESTADO        VARCHAR2(1) 
                    );

ALTER TABLE MASCOTAS ADD CONSTRAINT MASCOTAS_PK
PRIMARY KEY (ID); 

--V: VIVO, M: MUERTO
ALTER TABLE MASCOTAS ADD CONSTRAINT MASCOTAS_CK_1
CHECK (ESTADO IN ('V', 'M'))

ALTER TABLE MASCOTAS ADD CONSTRAINT MASCOTAS_CK_2
CHECK (ID            IS NOT NULL, 
       APODO_MASCOTA IS NOT NULL,
       ESTADO        IS NOT NULL)
	   
CREATE OR REPLACE PROCEDURE PRC_INTAB_MASCOTAS( ID NUMBER, APODO_MASCOTA VARCHAR2, ESTADO VARCHAR2 ) IS
BEGIN
    INSERT INTO RAMIRO.MASCOTAS
    VALUES(ID, APODO_MASCOTA, ESTADO);
    COMMIT;
END;
/
SHOW ERROR

PROMPT CONNECTANDOSE COMO MARIA
CONNECT MARIA/MARIA123;

CREATE TABLE EMPLEADOS ( ID      NUMBER(2), 
                         NOMBRE  VARCHAR2(10), 
                         SALARIO NUMBER(4) 
						);

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK
PRIMARY KEY (ID); 

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_CK_2
CHECK (ID      IS NOT NULL, 
       NOMBRE  IS NOT NULL,
       SALARIO IS NOT NULL)
	   
CREATE OR REPLACE PROCEDURE PRC_INS_EMPLEADOS ( ID NUMBER, NOMBRE VARCHAR2, SALARIO NUMBER ) IS
BEGIN
    INSERT INTO MARIA.EMPLEADOS
    VALUES(ID, NOMBRE, SALARIO);
    COMMIT;
END;
/
SHOW ERROR

PROMPT PARTE 2
PROMPT CREANDO USUARIOS (BOBY Y TOMMY)


PROMPT PARTE 3
PROMPT RAMIRO CREA ROLES Y ASIGNA PERMISOS
PROMPT CONNECTING AS RAMIRO
CONNECT RAMIRO/RAMIRO123

CREATE ROLE VET_CONSULTA;
CREATE ROLE VET_GERENTE;
CREATE ROLE VET_PROCESO;

GRANT SELECT 			ON MASCOTAS 			TO VET_CONSULTA;
GRANT UPDATE, DELETE 	ON MASCOTAS 			TO VET_GERENTE;
GRANT EXECUTE 			ON PRC_INTAB_MASCOTAS	TO VET_PROCESO;

GRANT VET_CONSULTA, VET_PROCESO TO BOBY;
GRANT VET_GERENTE TO TOMMY;
GRANT VET_CONSULTA, VET_PROCESO TO VET_GERENTE;

CREATE PUBLIC SYNONYM TAB_MASCOTAS FOR RAMIRO.MASCOTAS;
CREATE PUBLIC SYNONYM INS_MASCOTAS FOR RAMIRO.PRC_INTAB_MASCOTAS;

EXECUTE INS_MASCOTAS(00, 'FIRULAYS', 'V');
EXECUTE INS_MASCOTAS(01, 'PANCHA', 'M');

PROMPT PARTE 4
PROMPT MARIA CREA ROLES Y ASIGNA PERMISOS
PROMPT CONNECTING AS MARIA
CONNECT MARIA/MARIA123;

CREATE ROLE EMP_SEL;
CREATE ROLE EMP_JEFE;
CREATE ROLE EMP_PROCESO;

GRANT SELECT 			ON EMPLEADOS 			TO EMP_SEL;
GRANT UPDATE, DELETE 	ON EMPLEADOS 			TO EMP_JEFE;
GRANT EXECUTE 			ON PRC_INS_EMPLEADOS	TO EMP_PROCESO;

GRANT EMP_SEL, EMP_PROCESO TO TOMMY;
GRANT EMP_JEFE TO BOBY;
GRANT EMP_SEL, EMP_PROCESO TO EMP_JEFE;

CREATE PUBLIC SYNONYM EMPLEADOS3         FOR MARIA.EMPLEADOS;
CREATE PUBLIC SYNONYM PRC_INS_EMPLEADOS3 FOR MARIA.PRC_INS_EMPLEADOS;

EXECUTE PRC_INS_EMPLEADOS3(00, 'JUAN', 1000);
EXECUTE PRC_INS_EMPLEADOS3(01, 'JOSE', 5000);

PROMPT PARTE 5
PROMPT REALIZAR OPERACIONES CRUD A MASCOTAS Y EMPLEADOS CON BOBY Y TOMMY
PROMPT INTENTAR REALIZAR EL EXECUTE A AMBOS PROCESOS DE CADA TABLA

PROMPT CONNECTING AS BOBY
CONNECT BOBY/BOBY123;

PROMPT TRYING TO SELECT ON MASCOTAS AND EMPLEADOS
PROMPT !!! NO HAY ERRORES YA QUE BOBY TIENE PERMISOS DE EMP_JEFE Y VET_CONSULTA !!!
SELECT * FROM RAMIRO.MASCOTAS;
SELECT * FROM MARIA.EMPLEADOS;

PROMPT TRYING TO INSERT INTO MASCOTAS AND EMPLEADOS          
PROMPT !!! DOS ERRORES PORQUE A BOBY NO SE LE DIERON PERMISOS DE INSERTAR !!!
INSERT INTO RAMIRO.MASCOTAS VALUES(02, 'KUNA', 'V');
INSERT INTO MARIA.EMPLEADOS VALUES(02, 'YEEN', 9999);

PROMPT TRYING TO UPDATE MASCOTAS AND EMPLEADOS      
PROMPT !!! HAY UN ERROR EN MASCOTAS PORQUE BOBY SOLO TIENE PERMISOS DE VET_CONSULTA, VET_PROCESO !!!
UPDATE RAMIRO.MASCOTAS SET APODO_MASCOTA = 'KIWI' WHERE ID = 00;
UPDATE MARIA.EMPLEADOS SET NOMBRE = 'RITA' WHERE ID = 00;

PROMPT TRYING TO DELETE MASCOTAS AND EMPLEADOS 
PROMPT !!! HAY UN ERROR EN MASCOTAS PORQUE BOBY SOLO TIENE PERMISOS DE VET_CONSULTA, VET_PROCESO !!!
DELETE RAMIRO.MASCOTAS WHERE ID = 00;
DELETE MARIA.EMPLEADOS WHERE ID = 00;

PROMPT TRYING TO INSERT USING STORED PROCEDURES WITHOUT SYNONYMS     
PROMPT !!! NO HAY ERRORES BOBY TIENE PERMISO DE EJECUTAR !!!
EXECUTE INS_MASCOTAS(03, 'MELOCOTON', 'M');
EXECUTE PRC_INS_EMPLEADOS3(03, 'WALTER', 300);

PROMPT TRYING TO INSERT USING PUBLIC SYNONYM        
PROMPT !!! DOS ERRORES PORQUE BOBY NO TIENEN NINGUN PERMISO PARA SINONIMOS DE TABLAS !!!
INSERT INTO TAB_MASCOTAS 	VALUES (04, 'PERA', 'V');
INSERT INTO EMPLEADOS3 		VALUES (04, 'ERNESTO', 320);

PROMPT CONNECTING AS TOMMY
CONNECT TOMMY/TOMMY123;

PROMPT TRYING TO SELECT ON MASCOTAS AND EMPLEADOS
PROMPT !!! NO HAY ERRORES YA QUE TOMMY TIENE PERMISOS DE EMP_JEFE Y VET_CONSULTA !!!
SELECT * FROM RAMIRO.MASCOTAS;
SELECT * FROM MARIA.EMPLEADOS;

PROMPT TRYING TO INSERT INTO MASCOTAS AND EMPLEADOS          
PROMPT !!! DOS ERRORES PORQUE A TOMMY NO SE LE DIERON PERMISOS DE INSERTAR !!!
INSERT INTO RAMIRO.MASCOTAS VALUES(05, 'NEGRO', 'V');
INSERT INTO MARIA.EMPLEADOS VALUES(05, 'MONICA', 9999);

PROMPT TRYING TO UPDATE MASCOTAS AND EMPLEADOS      
PROMPT !!! HAY UN ERROR EN EMPLEADOS PORQUE TOMMY SOLO TIENE PERMISOS DE EMP_SEL, EMP_PROCESO !!!
UPDATE RAMIRO.MASCOTAS SET APODO_MASCOTA = 'KIWI' WHERE ID = 01;
UPDATE MARIA.EMPLEADOS SET NOMBRE = 'RITA' WHERE ID = 01;

PROMPT TRYING TO DELETE MASCOTAS AND EMPLEADOS 
PROMPT !!! HAY UN ERROR EN EMPLEADOS PORQUE TOMMY SOLO TIENE PERMISOS DE EMP_SEL, EMP_PROCESO !!!
DELETE RAMIRO.MASCOTAS WHERE ID = 01;
DELETE MARIA.EMPLEADOS WHERE ID = 01;

PROMPT TRYING TO INSERT USING STORED PROCEDURES WITHOUT SYNONYMS     
PROMPT !!! NO HAY ERRORES TOMMY TIENE PERMISO DE EJECUTAR !!!
EXECUTE INS_MASCOTAS(06, 'MASCOTA', 'M');
EXECUTE PRC_INS_EMPLEADOS3(06, 'GEORGINA', 300);

PROMPT TRYING TO INSERT USING PUBLIC SYNONYM        
PROMPT !!! DOS ERRORES PORQUE TOMMY NO TIENEN NINGUN PERMISO PARA SINONIMOS DE TABLAS !!!
INSERT INTO TAB_MASCOTAS 	VALUES (07, 'TUTU', 'V');
INSERT INTO EMPLEADOS3 		VALUES (07, 'YESSENIA', 320);
HOST PAUSE;


spool off





















