conn system/root

set linesize 250
set pagesize 100 

spool C:\bd2\pre-practica\logs\01_C_comprobacion.log

PROMPT OBJECTS IN OWNERS
SELECT OWNER, COUNT(*)
FROM    DBA_OBJECTS
WHERE   OWNER IN ('HR', 'HR5')
GROUP BY OWNER;

PROMPT TABLE NAMES
SELECT  OWNER OWN, TABLE_NAME
FROM    DBA_TABLES
WHERE   OWNER IN ('HR', 'HR5')
ORDER BY 1;

SELECT COUNT(*) HR_EMPLOYEES_ROWS
FROM HR.EMPLOYEES;

SELECT COUNT(*) HR5_EMPLOYEES_ROWS
FROM HR5.EMPLOYEES;

spool off
exit