SET LINESIZE 120
COLUMN OBJETO      FORMAT A15
COLUMN OS_USUARIO  FORMAT A20
COLUMN U_BLOQUEA   FORMAT A6
COLUMN PROGRAMA    FORMAT A15
COLUMN S_ID        FORMAT A6
COLUMN SER_NUM     FORMAT A6

SELECT OWNER||'.'||OBJECT_NAME Objeto,        OS_USER_NAME OS_USUARIO, 
       ORACLE_USERNAME U_BLOQUEA,        PROGRAM  PROGRAMA, 
       TO_CHAR(SESSION_ID) S_ID,        TO_CHAR(SERIAL#) SER_NUM
  FROM SYS.V_$LOCKED_OBJECT A, 
       SYS.ALL_OBJECTS B, 
       SYS.V_$SESSION c 
 WHERE A.OBJECT_ID = B.OBJECT_ID 
   AND C.SID = A.SESSION_ID 
ORDER BY 1;

DROP TABLE T2;
CREATE TABLE T2(A NUMBER);
ALTER TABLE T2 ADD CONSTRAINT T2_PK PRIMARY KEY (A);

INSERT INTO T2(A) VALUES (1);
INSERT INTO T2(A) VALUES (2);
