DROP TABLE T1;
DROP SEQUENCE S1;

CREATE TABLE T1(a number not null);
CREATE SEQUENCE S1 START WITH 1;

DECLARE
    X NUMBER := 0;
BEGIN
    WHILE X < 1000 LOOP
        INSERT INTO T1(a) VALUES (S1.NEXTVAL);
        X:= X + 1;  
    END LOOP;
    COMMIT;
END;
/
SELECT COUNT(*) FROM T1;

ALTER TABLE T1 ADD CONSTRAINT T1_PK PRIMARY KEY (a);