spool prepractica.log

HOST CLS;
CONNECT system/root

PROMPT PARTE 1
PROMPT DELETING, CREATING AND CONFIGURING NEW USERS (BOB AND TOM)
DROP USER BOB CASCADE;
DROP USER TOM CASCADE;

CREATE USER BOB IDENTIFIED BY BOB123;
CREATE USER TOM IDENTIFIED BY TOM123;

GRANT CREATE SESSION        TO BOB;
GRANT CREATE TABLE          TO BOB;
GRANT CREATE ROLES          TO BOB;
GRANT CREATE PROCEDURE      TO BOB;
GRANT CREATE PUBLIC SYNONYM TO BOB;

GRANT CREATE SESSION        TO TOM;
GRANT CREATE TABLE          TO TOM;
GRANT CREATE ROLES          TO TOM;
GRANT CREATE PROCEDURE      TO TOM;
GRANT CREATE PUBLIC SYNONYM TO TOM;

ALTER USER BOB QUOTA UNLIMITED ON SYSTEM;
ALTER USER TOM QUOTA UNLIMITED ON SYSTEM;

PROMPT CONNECTING AS BOB
CONNECT BOB/BOB123

CREATE TABLE FRUTAS ( ID        NUMBER(2), 
                      NOM_FRUTA VARCHAR2(10), 
                      ESTADO    VARCHAR2(1) 
                    );

ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_PK
PRIMARY KEY (ID); 

--A: ACTIVE, I: INACTIVE
ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_CK_1
CHECK (ESTADO IN ('A', 'I'))

ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_CK_2
CHECK (ID        IS NOT NULL, 
       NOM_FRUTA IS NOT NULL,
       ESTADO    IS NOT NULL)

CREATE OR REPLACE PROCEDURE PRC_INS_FRUTAS( ID NUMBER, NOM_FRUTA VARCHAR2, ESTADO VARCHAR2 ) IS
BEGIN
    INSERT INTO FRUTAS 
    VALUES(ID, NOM_FRUTA, ESTADO);
    COMMIT;
END;
/
SHOW ERROR


PROMPT CONNECTING AS TOM
CONNECT TOM/TOM123

CREATE TABLE ACTIVOS( ID            NUMBER(2),
                      NOM_ACTIVO    VARCHAR2(10),
                      MESES         NUMBER(2) );

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_PK
PRIMARY KEY (ID);

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_CK_1
CHECK (MESES BETWEEN (1, 36));

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_CK_2
CHECK (ID           IS NOT NULL, 
       NOM_ACTIVO   IS NOT NULL,
       MESES        IS NOT NULL)

CREATE OR REPLACE PROCEDURE PRC_INS_ACTIVOS( ID NUMBER, NOM_ACTIVO VARCHAR2, MESES NUMBER ) IS
BEGIN 
    INSERT INTO ACTIVOS 
    VALUES(ID, NOM_ACTIVO, MESES);
    COMMIT;
END;
/
SHOW ERROR

HOST PAUSE;

PROMPT PARTE 2
PROMPT DELETING, CREATING AND CONFIGURING NEW USERS (MARY AND SUSAN)

CONNECT system/root

DROP USER SUSAN CASCADE; 
DROP USER MARY  CASCADE;

CREATE USER SUSAN IDENTIFIED BY SUSAN123;
CREATE USER MARY  IDENTIFIED BY MARY123;

GRANT CREATE SESSION TO SUSAN; 
GRANT CREATE SESSION TO MARY;

HOST PAUSE;

PROMPT PARTE 3
PROMPT BOBs ROLES FOR CORRESPONDING NEW USERS

CONNECT system/root

DROP ROLE FRT_CONSULTA;
DROP ROLE FRT_ADMIN;
DROP ROLE FRT_EJECUTA;

DROP PUBLIC SYNONYM S_FRUTAS;
DROP PUBLIC SYNONYM S_PRC_INS_FRUTAS;

CONNECT BOB/BOB123

CREATE ROLE FRT_CONSULTA;
CREATE ROLE FRT_ADMIN;
CREATE ROLE FRT_EJECUTA;

GRANT SELECT ON FRUTAS TO FRT_CONSULTA;
GRANT UPDATE, DELETE ON FRUTAS TO FRT_ADMIN;
GRANT EXECUTE ON PRC_INS_FRUTAS TO FRT_EJECUTA;

GRANT FRT_CONSULTA, FRT_EJECUTA TO MARY;
GRANT FRT_ADMIN TO SUSAN;

CREATE PUBLIC SYNONYM S_FRUTAS          FOR FRUTAS.PRC_INS_FRUTAS;
CREATE PUBLIC SYNONYM S_PRC_INS_FRUTAS  FOR FRUTAS.PRC_INS_FRUTAS;

EXECUTE PRC_INS_FRUTAS(00, 'BANANO', 'A');
EXECUTE PRC_INS_FRUTAS(01, 'SANDIA', 'A');

HOST PAUSE;

PROMPT PARTE 4
PROMPT TOMs ROLES FOR CORRESPONDING NEW USERS

CONNECT system/root

DROP ROLE ACT_CONSULTA;
DROP ROLE ACT_ADMIN;
DROP ROLE ACT_EJECUTA;

DROP PUBLIC SYNONYM ACTIVOS2;
DROP PUBLIC SYNONYM PRC_INS_ACTIVOS2;

CONNECT TOM/TOM123

CREATE ROLE ACT_CONSULTA;
CREATE ROLE ACT_ADMIN;
CREATE ROLE ACT_EJECUTA;

GRANT SELECT ON ACTIVOS TO ACT_CONSULTA;
GRANT UPDATE, DELETE ON ACTIVOS TO ACT_ADMIN;
GRANT EXECUTE ON PRC_INS_ACTIVOS TO ACT_EJECUTA;

GRANT ACT_CONSULTA, ACT_EJECUTA TO SUSAN;
GRANT ACT_ADMIN TO MARY;

CREATE PUBLIC SYNONYM ACTIVOS2          FOR ACTIVOS.PRC_INS_ACTIVOS;
CREATE PUBLIC SYNONYM PRC_INS_ACTIVOS2  FOR ACTIVOS.PRC_INS_ACTIVOS;

EXECUTE PRC_INS_ACTIVOS(00, 'WHAAT', 5);
EXECUTE PRC_INS_ACTIVOS(01, 'WHERE', 7);

spool off