spool prepractica.log

HOST CLS;
CONNECT system/root

PROMPT PARTE 1
PROMPT DELETING, CREATING AND CONFIGURING NEW USERS (BOB AND TOM)
DROP USER BOB CASCADE;
DROP USER TOM CASCADE;

CREATE USER BOB IDENTIFIED BY BOB123;
CREATE USER TOM IDENTIFIED BY TOM123;

GRANT CREATE SESSION        TO BOB;
GRANT CREATE TABLE          TO BOB;
GRANT CREATE ROLES          TO BOB;
GRANT CREATE PROCEDURE      TO BOB;
GRANT CREATE PUBLIC SYNONYM TO BOB;

GRANT CREATE SESSION        TO TOM;
GRANT CREATE TABLE          TO TOM;
GRANT CREATE ROLES          TO TOM;
GRANT CREATE PROCEDURE      TO TOM;
GRANT CREATE PUBLIC SYNONYM TO TOM;

ALTER USER BOB QUOTA UNLIMITED ON SYSTEM;
ALTER USER TOM QUOTA UNLIMITED ON SYSTEM;

PROMPT CONNECTING AS BOB
CONNECT BOB/BOB123

CREATE TABLE FRUTAS ( ID        NUMBER(2), 
                      NOM_FRUTA VARCHAR2(10), 
                      ESTADO    VARCHAR2(1) 
                    );

ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_PK
PRIMARY KEY (ID); 

--A: ACTIVE, I: INACTIVE
ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_CK_1
CHECK (ESTADO IN ('A', 'I'))

ALTER TABLE FRUTAS ADD CONSTRAINT FRUTAS_CK_2
CHECK (ID        IS NOT NULL, 
       NOM_FRUTA IS NOT NULL,
       ESTADO    IS NOT NULL)

CREATE OR REPLACE PROCEDURE PRC_INS_FRUTAS( ID NUMBER, NOM_FRUTA VARCHAR2, ESTADO VARCHAR2 ) IS
BEGIN
    INSERT INTO BOB.FRUTAS 
    VALUES(ID, NOM_FRUTA, ESTADO);
    COMMIT;
END;
/
SHOW ERROR


PROMPT CONNECTING AS TOM
CONNECT TOM/TOM123

CREATE TABLE ACTIVOS( ID            NUMBER(2),
                      NOM_ACTIVO    VARCHAR2(10),
                      MESES         NUMBER(2) );

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_PK
PRIMARY KEY (ID);

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_CK_1
CHECK (MESES BETWEEN (1, 36))

ALTER TABLE ACTIVOS ADD CONSTRAINT ACTIVOS_CK_2
CHECK (ID           IS NOT NULL, 
       NOM_ACTIVO   IS NOT NULL,
       MESES        IS NOT NULL)

CREATE OR REPLACE PROCEDURE PRC_INS_ACTIVOS( ID NUMBER, NOM_ACTIVO VARCHAR2, MESES NUMBER ) IS
BEGIN 
    INSERT INTO TOM.ACTIVOS 
    VALUES(ID, NOM_ACTIVO, MESES);
    COMMIT;
END;
/
SHOW ERROR

HOST PAUSE;

PROMPT PARTE 2
PROMPT DELETING, CREATING AND CONFIGURING NEW USERS (MARY AND SUSAN)

PROMPT CONNECTING AS System Admin
CONNECT system/root

DROP USER SUSAN CASCADE; 
DROP USER MARY  CASCADE;

CREATE USER SUSAN IDENTIFIED BY SUSAN123;
CREATE USER MARY  IDENTIFIED BY MARY123;

GRANT CREATE SESSION TO SUSAN; 
GRANT CREATE SESSION TO MARY;

HOST PAUSE;

PROMPT PARTE 3
PROMPT BOBs ROLES FOR CORRESPONDING NEW USERS

PROMPT CONNECTING AS System Admin
CONNECT system/root

DROP ROLE FRT_CONSULTA;
DROP ROLE FRT_ADMIN;
DROP ROLE FRT_EJECUTA;

DROP PUBLIC SYNONYM S_FRUTAS;
DROP PUBLIC SYNONYM S_PRC_INS_FRUTAS;

PROMPT CONNECTING AS BOB
CONNECT BOB/BOB123

CREATE ROLE FRT_CONSULTA;
CREATE ROLE FRT_ADMIN;
CREATE ROLE FRT_EJECUTA;

GRANT SELECT ON FRUTAS TO FRT_CONSULTA;
GRANT UPDATE, DELETE ON FRUTAS TO FRT_ADMIN;
GRANT EXECUTE ON PRC_INS_FRUTAS TO FRT_EJECUTA;

GRANT FRT_CONSULTA, FRT_EJECUTA TO MARY;
GRANT FRT_ADMIN TO SUSAN;

CREATE PUBLIC SYNONYM S_FRUTAS          FOR BOB.FRUTAS;
CREATE PUBLIC SYNONYM S_PRC_INS_FRUTAS  FOR BOB.PRC_INS_FRUTAS;

EXECUTE PRC_INS_FRUTAS(00, 'BANANO', 'A');
EXECUTE PRC_INS_FRUTAS(01, 'SANDIA', 'A');

HOST PAUSE;

PROMPT PARTE 4
PROMPT TOMs ROLES FOR CORRESPONDING NEW USERS

PROMPT CONNECTING AS System Admin
CONNECT system/root

DROP ROLE ACT_CONSULTA;
DROP ROLE ACT_ADMIN;
DROP ROLE ACT_EJECUTA;

DROP PUBLIC SYNONYM ACTIVOS2;
DROP PUBLIC SYNONYM PRC_INS_ACTIVOS2;

PROMPT CONNECTING AS TOM
CONNECT TOM/TOM123

CREATE ROLE ACT_CONSULTA;
CREATE ROLE ACT_ADMIN;
CREATE ROLE ACT_EJECUTA;

GRANT SELECT ON ACTIVOS TO ACT_CONSULTA;
GRANT UPDATE, DELETE ON ACTIVOS TO ACT_ADMIN;
GRANT EXECUTE ON PRC_INS_ACTIVOS TO ACT_EJECUTA;

GRANT ACT_CONSULTA, ACT_EJECUTA TO SUSAN;
GRANT ACT_ADMIN TO MARY;

CREATE PUBLIC SYNONYM ACTIVOS2          FOR TOM.ACTIVOS;
CREATE PUBLIC SYNONYM PRC_INS_ACTIVOS2  FOR TOM.PRC_INS_ACTIVOS;

EXECUTE PRC_INS_ACTIVOS(00, 'WHAAT', 5);
EXECUTE PRC_INS_ACTIVOS(01, 'WHERE', 7);

PROMPT PARTE 5
PROMPT DOING INSERTS WITH SUSAN AND MARY INTO FRUTAS AND ACTIVOS

PROMPT CONNECTING AS MARY
CONNECT MARY/MARY123

PROMPT TRYING TO SELECT ON FRUTAS AND ACTIVOS                !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO SELECT ( ACTIVOS)
SELECT * FROM BOB.FRUTAS;
SELECT * FROM TOM.ACTIVOS;

PROMPT TRYING TO INSERT INTO FRUTAS AND ACTIVOS            !! TWO ERRORS ABOUT INSUFICIENT PRIVILEGES TO INSERT (FRUTAS, ACTIVOS)
INSERT INTO BOB.FRUTAS VALUES(02, 'FRESA', 'A');
INSERT INTO TOM.ACTIVOS VALUES(02, 'HOOW', 8);

PROMPT TRYING TO UPDATE FRUTAS AND ACTIVOS                  !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO UPDATE (FRUTAS)
UPDATE BOB.FRUTAS SET NOM_FRUTA = 'KIWI' WHERE ID = 00;
UPDATE TOM.ACTIVOS SET NOM_ACTIVO = 'HELLOOOO' WHERE ID = 00;

PROMPT TRYING TO DELETE FRUTAS AND ACTIVOS                  !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO DELETE (FRUTAS)
DELETE BOB.FRUTAS WHERE ID = 00;
DELETE TOM.ACTIVOS WHERE ID = 00;

PROMPT TRYING TO INSERT USING STORED PROCEDURES WITHOUT SYNONYMS                !! ONE ERROR ABOUT NOT DECLARING PROCEDURE (ACTIVOS) 
EXECUTE BOB.PRC_INS_FRUTAS(03, 'MELOCOTON', 'I');
EXECUTE TOM.PRC_INS_ACTIVOS(03, 'ME CAGO', 30);

PROMPT TRYING TO INSERT USING PUBLIC SYNONYM                                    !! TWO ERRORS ABOUT INSUFICIENT PRIVILEGES TO INSERT (FRUTAS, ACTIVOS)
INSERT INTO S_FRUTAS VALUES (04, 'PERA', 'I');
INSERT INTO ACTIVOS2 VALUES (04, 'QUE ES ESTO', 32);


PROMPT CONNECTING AS SUSAN
CONNECT SUSAN/SUSAN123
-- NOT FINISHED JUST YET    
PROMPT TRYING TO SELECT ON FRUTAS AND ACTIVOS                !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO SELECT ( ACTIVOS)
SELECT * FROM BOB.FRUTAS;
SELECT * FROM TOM.ACTIVOS;

PROMPT TRYING TO INSERT INTO FRUTAS AND ACTIVOS            !! TWO ERRORS ABOUT INSUFICIENT PRIVILEGES TO INSERT (FRUTAS, ACTIVOS)
INSERT INTO BOB.FRUTAS VALUES(05, 'GILIPOLLAS', 'A');
INSERT INTO TOM.ACTIVOS VALUES(05, 'LGBT', 10);

PROMPT TRYING TO UPDATE FRUTAS AND ACTIVOS                  !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO UPDATE (FRUTAS)
UPDATE BOB.FRUTAS SET NOM_FRUTA = 'KIWITA' WHERE ID = 01;
UPDATE TOM.ACTIVOS SET NOM_ACTIVO = 'HELLOOWA' WHERE ID = 01;

PROMPT TRYING TO DELETE FRUTAS AND ACTIVOS                  !! ONE ERROR ABOUT INSUFICIENT PRIVILEGES TO DELETE (FRUTAS)
DELETE BOB.FRUTAS WHERE ID = 01;
DELETE TOM.ACTIVOS WHERE ID = 01;

PROMPT TRYING TO INSERT USING STORED PROCEDURES WITHOUT SYNONYMS                !! ONE ERROR ABOUT NOT DECLARING PROCEDURE (ACTIVOS) 
EXECUTE BOB.PRC_INS_FRUTAS(05, 'MECHIMA', 'I');
EXECUTE TOM.PRC_INS_ACTIVOS(05, 'MECHIMA', 35);

PROMPT TRYING TO INSERT USING PUBLIC SYNONYM                                    !! TWO ERRORS ABOUT INSUFICIENT PRIVILEGES TO INSERT (FRUTAS, ACTIVOS)
INSERT INTO S_FRUTAS VALUES (06, 'PERAPOD', 'I');
INSERT INTO ACTIVOS2 VALUES (06, 'QUE JESTO', 32);


spool off